version: '3'
services:
  backup:
    build: .
    env_file:
      - .env
    environment:
      - "MONGO_URI=mongo:27017"
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_AUTH_DB
      - AZURE_SA
      - AZURE_BLOB_CONTAINER
      - AZURE_SHARE_NAME
      - AZURE_DESTINATION_KEY
      - DB
    depends_on:
      - mongo
  mongo:
    image: "bitnami/mongodb:4.0"
